### ISSUE TITLE
Make sure the blueprints for all functions in the code are ok.

### ISSUE THREAD

**Issue by LunarTides** [LunarTides/Hearthstone.js#19]
The blueprints for function look something like this:
```js
playCard(card: Card, player: Player) -> str | Card
summonMinion(card: Card, player: Player, update: bool, trigger_colossal: bool) -> Card
```

Make sure all of these look ok. The actual code for the functions don't really matter as long as it conforms to the blueprint. This is important so that cards can last as long as possible without maintenance.

**Comment by IsakSkole123** [comment]
I know this is probably a good idea, but I will shelf it for now. Feel free to reopen at some point in the future.
