### ISSUE TITLE
Reimplement every single card.

### ISSUE THREAD

**Issue by LunarTides** [LunarTides/Hearthstone.js#20]
Many cards are very old and so should be rewritten. The best way to do this is just to delete every single card added to the game, then reimplement the cards in the decks in decks.json.

This is very low priority since it is a massive commitment.

Add any breaking changes that could be added while doing this below:
`Add "Collectible" and "Uncollectible" folders in the card creator inside the class folder`
`Change the name of all the passives` - #39

**Comment by IsakSkole123** [comment]
Also add "Collectible" and "Uncollectible" folders in the card creator inside the class folder

**Comment by SolarWindss** [comment]
Also change the name of all the passives
