### ISSUE TITLE
Add random deck choosing

### ISSUE THREAD

**Issue by LunarTides** [LunarTides/Hearthstone.js#23]
Find a way to add random deck choosing from exported decks since this got accidentally patched out in commit 24c24ca.

**Comment by SolarWindss** [comment]
Closing since this is not a priority. I want to focus my time towards more important issues.

**Comment by IsakSkole123** [comment]
Reopening this, but won't give it a milestone. Do this whenever.

**Comment by LunarTides** [comment]
This is no longer possible.
